INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:50:00', 'Una deliziosa pizza con mozzarella, pomodoro e basilico.', 'https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg', 'Pizza Margherita', 8.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:51:00', 'Una pizza classica con pepperoni e formaggio fuso.', 'https://cdn.tasteatlas.com/images/dishes/b05a0af72ad845f3a6abe16143d7853a.jpg?m=facebook', 'Pizza Pepperoni', 9.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:52:00', 'Una pizza con prosciutto, funghi, carciofi e olive.', 'https://www.petitchef.it/imgupl/recipe/pizza-quattro-stagioni--327908p533338.jpg', 'Pizza Quattro Stagioni', 10.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:53:00', 'Pizza con prosciutto, funghi e una base di pomodoro.', 'https://www.pizzeriasenzatempo.it/wp-content/uploads/2020/04/PROSCIUTTO-E-FUNGHI.jpg', 'Pizza Prosciutto Funghi', 9.49);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:54:00', 'Una pizza piccante con salame piccante e peperoncini.', 'https://www.silviocicchi.com/pizzachef/wp-content/uploads/2015/03/d1.jpg', 'Pizza Diavola', 10.49);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:55:00', 'Una pizza tropicale con prosciutto e ananas.', 'https://www.fruttaweb.com/consigli/wp-content/uploads/2019/07/shutterstock_84904861.jpg', 'Pizza Hawaii', 11.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:56:00', 'Pizza con prosciutto, carciofi, olive e funghi.', 'https://www.melarossa.it/wp-content/uploads/2021/02/pizza-capricciosa.jpg', 'Pizza Capricciosa', 11.49);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:57:00', 'Una pizza semplice con aglio, pomodoro e basilico.', 'https://www.giallozafferano.it/images/154-15407/Pizza-marinara_650x433_wm.jpg', 'Pizza Marinara', 8.49);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:58:00', 'Pizza con una selezione di quattro formaggi.', 'https://primochef.it/wp-content/uploads/2020/04/SH_pizza_quattro_stagioni.jpg', 'Pizza Quattro Formaggi', 12.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 14:59:00', 'Pizza con tonno, cipolla, olive e pomodoro.', 'https://blog.giallozafferano.it/cucinoperpassione/wp-content/uploads/2019/09/Pizza-rossa-tonno-e-cipolla.jpg', 'Pizza Tonno e Cipolla', 10.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:00:00', 'Una pizza napoletana con acciughe e capperi.', 'https://www.donnamoderna.com/content/uploads/2021/08/pizza-napoli-830x625.jpg', 'Pizza Napoletana', 9.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:01:00', 'Una variante della classica Margherita con mozzarella di bufala.', 'https://www.mypizzamoments.com/wp-content/uploads/2017/03/MyPizza-Margherita-extra-1024x683.jpeg', 'Pizza Margherita Extra', 11.49);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:02:00', 'Una deliziosa pizza vegetariana con verdure fresche.', 'https://www.guardini.com/images/guardinispa/ricette/full/pizza_set_2021_full.jpg', 'Pizza Vegetariana', 10.49);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:03:00', 'Pizza con ricotta, mozzarella, parmigiano e pepe nero.', 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2023/03/Pizza-mimosa-1200x675.jpg', 'Pizza Bianca', 9.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:04:00', 'Una pizza cremosa con pancetta, uova e formaggio.', 'https://www.pizzatales.it/wp50/wp-content/uploads/2021/10/la-pizza-alla-carbonara.jpg', 'Pizza Carbonara', 12.49);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:05:00', 'Una pizza con rucola fresca e prosciutto crudo.', 'https://blog.giallozafferano.it/primipiattiricette/wp-content/uploads/2015/10/gluten-free-pizza.jpg', 'Pizza Rucola e Prosciutto', 12.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:06:00', 'Una pizza piegata a calzone ripiena di prosciutto e formaggio.', 'https://img.comeunochef.com/2020-11/calzone-napoletano-1.jpg', 'Pizza Calzone', 11.49);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:07:00', 'Pizza con una selezione mista di frutti di mare.', 'https://wips.plug.it/cips/buonissimo.org/cms/2012/05/pizza-ai-frutti-di-mare.jpg', 'Pizza Frutti di Mare', 13.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:08:00', 'Una pizza ispirata ai sapori della Sicilia.', 'https://www.strapizza.it/media/k2/items/cache/af2ef6a0e2c9c528b09655df79f3b312_XL.jpg', 'Pizza Siciliana', 11.99);
INSERT INTO pizze (created_at, description, image, name, price) VALUES ('2023-11-09 15:09:00', 'Pizza con funghi, mozzarella e prelibate erbe aromatiche.', 'https://ohmydish.com/wp-content/uploads/2017/07/Pizza-funghi.jpg', 'Pizza Funghi', 9.49);
INSERT INTO ingredients (name) VALUES ('Mozzarella');
INSERT INTO ingredients (name) VALUES ('Pomodoro');
INSERT INTO ingredients (name) VALUES ('Funghi');
INSERT INTO ingredients (name) VALUES ('Peperoni');
INSERT INTO ingredients (name) VALUES ('Prosciutto');
INSERT INTO ingredients (name) VALUES ('Salsiccia');
INSERT INTO ingredients (name) VALUES ('Olive');
INSERT INTO ingredients (name) VALUES ('Capperi');
INSERT INTO ingredients (name) VALUES ('Ananas');
INSERT INTO ingredients (name) VALUES ('Tonno');
INSERT INTO ingredients (name) VALUES ('Formaggio Gorgonzola');
INSERT INTO ingredients (name) VALUES ('Rucola');
INSERT INTO ingredients (name) VALUES ('Parmigiano Reggiano');
INSERT INTO ingredients (name) VALUES ('Cipolla');
INSERT INTO ingredients (name) VALUES ('Peperoncino');
INSERT INTO ingredients (name) VALUES ('Zucchine');
INSERT INTO ingredients (name) VALUES ('Melanzane');
INSERT INTO ingredients (name) VALUES ('Provolone');
INSERT INTO ingredients (name) VALUES ('Bresaola');
INSERT INTO ingredients (name) VALUES ('Salame');
INSERT INTO ingredients (name) VALUES ('Champignon');
INSERT INTO ingredients (name) VALUES ('Pancetta');
INSERT INTO ingredients (name) VALUES ('Pomodorini');
INSERT INTO ingredients (name) VALUES ('Gamberetti');
INSERT INTO ingredients (name) VALUES ('Zola');
INSERT INTO ingredients (name) VALUES ('Feta');
INSERT INTO ingredients (name) VALUES ('Ricotta');
INSERT INTO ingredients (name) VALUES ('Salmone');
INSERT INTO ingredients (name) VALUES ('Acciughe');
INSERT INTO ingredients (name) VALUES ('Mais');
INSERT INTO ingredients (name) VALUES ('Paprika');
INSERT INTO ingredients (name) VALUES ('Pepe Nero');
INSERT INTO ingredients (name) VALUES ('Pesto');
INSERT INTO ingredients (name) VALUES ('Bacon');
INSERT INTO ingredients (name) VALUES ('Gorgonzola Dolce');
INSERT INTO ingredients (name) VALUES ('Carciofi');
INSERT INTO ingredients (name) VALUES ('Cetriolini');
INSERT INTO ingredients (name) VALUES ('Pesto Rosso');
INSERT INTO ingredients (name) VALUES ('Asparagi');
INSERT INTO ingredients (name) VALUES ('Fungi Porcini');